### ISSUE TITLE
Support livewire 3

### ISSUE THREAD

**Issue by Saifallak** [spatie/laravel-enum#101]
Reference https://github.com/livewire/livewire/discussions/5885

Livewire 3 doesn't support Spatie enums like Livewire 2

can be solved by https://livewire.laravel.com/docs/synthesizers

might be related to https://github.com/spatie/laravel-enum/issues/100

**Comment by Saifallak** [comment]
..

**Comment by Saifallak** [comment]
> Instead of spamming the issue with your dots you could open a PR and fix your issue.

nope, not spamming, just keeping the issue open.
sorry if i pinged you by mistake,

**Comment by booni3** [comment]
This does not quite work when model casting is thrown into the mix. You can use a syntesizer like so:

```php
<?php

namespace Domain\Issue\Enum;

use Livewire\Mechanisms\HandleComponents\Synthesizers\EnumSynth as BaseEnumSynth;
use Spatie\Enum\Enum;

class EnumSynth extends BaseEnumSynth
{
    public static $key = 'spatie-enum';

    static function match($target): bool {
        return $target instanceof Enum;
    }
}
```
