### ISSUE TITLE
TravisCI is super slow

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-enum#15]
A single build needs around 5min
https://travis-ci.org/spatie/laravel-enum/builds/567966674

It seems that the slowest part is `composer update` because of the `--prefer-source` flag and/or no caching.

**Comment by brendt** [comment]
I believe this is the setup for all our packages at the moment. If travis is able to cache the vendor folder if lock files weren't changed, we could look into that. I'll discuss it here at the office.

**Comment by brendt** [comment]
Edit: hang on, I just realised we obviously don't add lock files to packages 🤪

I believe @AlexVanderbist looked into this problem before though, maybe he has some input?

**Comment by brendt** [comment]
Apparently you already submitted a PR which I hadn't seen yet: #16
