### ISSUE TITLE
Laravel 7 custom casts

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-enum#31]
https://github.com/laravel/framework/pull/31035
https://github.com/laravel/framework/pull/32129

**Comment by Skullbock** [comment]
Hey @Gummibeer if you want i implemented in one of my project this.
It's still rough, but it allows you to use the cast class directly, without needing a trait:

```php
 /**
     * @var string[]
     */
    protected $casts = [
        'color'           => ColorEnum::class
    ];
```


The basic idea is:

```php
abstract class Enum extends \Spatie\Enum\Enum implements \Illuminate\Contracts\Database\Eloquent\Castable
{
    public static function castUsing()
    {
        return EnumCast::class;
    }

    protected static function resolveFromStaticMethods(\ReflectionClass $reflection): array
    {
        $methods = parent::resolveFromStaticMethods($reflection);

        unset($methods[array_search('castUsing', $methods)]);

        return $methods;
    }
}
```

where ```EnumCast``` is:

```php
class EnumCast implements \Illuminate\Contracts\Database\Eloquent\CastsAttributes
{
    private ?string $enumClass;

    public function __construct(?string $enumClass = null)
    {
        $this->enumClass = $enumClass;
    }

    public function get($model, $key, $value, $attributes)
    {
        if ($value === null) {
            return $value;
        }

        $class = $this->enumClass ?: $model->getCasts()[$key];
        if (!$value instanceof Enum) {
            $value = $class::make($value);
        }

        return $value;
    }
    public function set($model, $key, $value, $attributes)
    {
        if (!$value instanceof Enum) {
            return $value;
        }

        return (string) $value;
    }
}
```

**Comment by Gummibeer** [comment]
Hey @Skullbock sorry that I haven't linked the PR.
The casting is already done in #44 right now the dropped `$enums` property in the trait brings an issue for the scopes.
That's why it's not merged already.

**Comment by Skullbock** [comment]
Ah sorry, didn't see that. 
You PR'ed solution is way more advanced than mine so i'll use that when released.

Just my 2 cents, my solution, while way less flexible than yours, has 1 small advantage in terms of DX: you can see the class being casted directly there, as an autocompletable and IDE navigatable class, instead of a string as it is in your case. It's a small thing, but still i though worth it to point it out.

```php
 /**
     * @var string[]
     */
    protected $casts = [
        'color'           => ColorEnum::class
    ];
```

Cheers!

**Comment by Gummibeer** [comment]
Hey,

we have introduced multiple casts (4) so we can't deliver a ready to use enum defining the `castUsing()` method. But we will add an example showing this option to the docs.
I totally love this feature added by @brendt !
What we will prepare is a way to exclude static methods from resolving the enum. Will check which way we will use, but I think that a special doc-comment annotation will be the easiest for all.

**Comment by Skullbock** [comment]
Gotcha, gonna wait eagerly for that PR to be merged in

**Comment by Gummibeer** [comment]
Me too, but right now we have some big issues with the scopes. We will have to discuss if we drop the scopes at all or if we have to limit the usability to the most common usecases, expect a given input (real enum instances instead of strings and ints and enumerables mixed) or write some pretty complex magic to let them work the same like right now.
I'm thinking about merging the custom cast classes in addition to the trait in the current v1. But will wait some time for response regarding the scopes topic at first.
