### ISSUE TITLE
Trait 'Spatie\Enum\HasEnums' not found

### ISSUE THREAD

**Issue by Patabugen** [spatie/laravel-enum#32]
In README.md the example shows:

```
use Spatie\Enum\HasEnums;
```

but I believe this should be:
```
use Spatie\Enum\Laravel\HasEnums;
```

I can make a PR if you can confirm that's correct (and a PR is easier than you correcting it directly).

**Comment by Gummibeer** [comment]
Thanks! You are right and I would be happy to merge your PR! 😊

**Comment by Gummibeer** [comment]
Thanks to @Owlnofeathers for fixing it :)
