### ISSUE TITLE
Command incorrect in README

### ISSUE THREAD

**Issue by lessevv** [spatie/laravel-enum#36]
Within the README.md, the following artisan command is given as an example:
`php artisan enum:make StatusEnum`

However, this seems to be incorrect, and the correct command is the other way around:
`php artisan make:enum StatusEnum`

I've created the following PR to fix this typo:
https://github.com/spatie/laravel-enum/pull/35

**Comment by Gummibeer** [comment]
Thanks, you are 100% right. 👍
