### ISSUE TITLE
getIndex return value when used in a factory

### ISSUE THREAD

**Issue by vizko** [spatie/laravel-enum#37]
Hello,

When using the enums inside a factory it always return the value and not the index. 

Example : 
```php
$factory->define(User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'remember_token' => Str::random(10),
        'account_type' => AccountType::USER()->getIndex(),
    ];
});
``` 
```
>>> factory('App\User')->make();
=> App\User {#3082
     name: "Roxanne Terry-test",
     email: "iprohaska@example.com",
     email_verified_at: "2020-03-23 14:02:45",
     account_type: "USER",
```

the same happens when I try to override the field : 
```
>>> factory('App\User')->make(['account_type' => App\Enums\AccountType::USER()->getIndex()]);
=> App\User {#3069
     name: "Ms. Vella Buckridge DVM",
     email: "dorthy93@example.org",
     email_verified_at: "2020-03-23 14:04:31",
     account_type: "USER",
   }
```

But if I use a default value in my migration it work as expected 
```php
$table->integer('account_type')->unsigned()->default(AccountType::USER()->getIndex());
```

```
>>> factory('App\User')->create();
=> App\User {#3070
     name: "Prof. Sylvester Bartoletti Sr.",
     email: "yhermann@example.net",
     email_verified_at: "2020-03-23 14:09:37",
     updated_at: "2020-03-23 14:09:37",
     created_at: "2020-03-23 14:09:37",
     id: 1,
   }
>>> App\User::find(1);
=> App\User {#3079
     id: "1",
     name: "Prof. Sylvester Bartoletti Sr.",
     email: "yhermann@example.net",
     email_verified_at: "2020-03-23 14:09:37",
     account_type: "0",
     created_at: "2020-03-23 14:09:37",
     updated_at: "2020-03-23 14:09:37",
   }
```

edit: I use laravel-enums so maybe related idk.

**Comment by Gummibeer** [comment]
Hey,

I've moved the issue in the `laravel-enum` package.

Do you want to store the index in the database instead of it's value?
In this case you will have to set the attribute cast to `int`.

https://github.com/spatie/laravel-enum#model-attribute-casting
> In some cases, enums should be stored as integer (index) in the database.
> By using the $casts property you can cast your status attribute to int or integer and the trait will store the index instead of the value.

For the dump I don't know what it does, but it could be that it does some magic in the background.

**Comment by vizko** [comment]
Casting to int fix my problem thanks 👍

**Comment by Gummibeer** [comment]
Happy that it solved your issue! If you have an idea how we could improve the readme - let me know or feel free to submit a PR. :)
