### ISSUE TITLE
model attribute cast array of enums

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-enum#38]
We have a multiselect/checkboxes - every of these options is a value of the same enum.

```php
foreach($enum->values() as $value) {
    echo '<checkbox value="'.$value.'"/>';
}
```

And on the model we save this in a JSON column. like we already introduced the `:nullable` flag - how about being able to add a `array` flag or even better use the `[]` notation behind the enum class name.

Because the new Laravel 7 object custom casts work pretty much the same like our current notation we should/could add this feature before dropping Laravel 6 support.

```
MyEnum::class
MyEnum::class.':nullable'
// options for new array cast  feature
MyEnum::class.'[]:nullable'
MyEnum::class.':nullable,array'
```

The expected result would be an array of enum instances `Enumerable[]`.

**Comment by brendt** [comment]
If you'd do this, I'd definitely choose the `MyEnum::class.':nullable,array'` syntax. I think I would make a dedicated `EnumCollection` cast for clarity, but that's merely preference.

**Comment by Gummibeer** [comment]
Okay, I will use the `array` flag for the current implementation and switch to the `EnumCollection` cast for the Laravel 7 release.
