### ISSUE TITLE
Make command gives incomplete output

### ISSUE THREAD

**Issue by sestolk** [spatie/laravel-enum#40]
I just started using this package and after installation I created a new Enum using the `php artisan make:enum FooEnum` command.

It created the Enum just fine however the command output is incomplete and only shows:

` created successfully.`

Instead of what I think it should have been:

`FooEnum created successfully.`

**Comment by Gummibeer** [comment]
Hey,
Should be easy to fix.
Because it's a candy request I will flag it for contributors to add. Most times this works pretty well and for sure you can send a PR by yourself. 😉

**Comment by rossjcooper** [comment]
@oliversarfas 😆

**Comment by oliversarfas** [comment]
I think a mix of both our methods would be ideal! I also forgot to change the title of my PR 🤦‍♂️

Didn't see the `getNameInput()` method - very handy and a good time to use it here.

**Comment by Gummibeer** [comment]
It's solved :)
Thanks everyone!
https://github.com/spatie/laravel-enum/releases/tag/1.5.0
