### ISSUE TITLE
HasEnums trait collides with HasTranslations trait

### ISSUE THREAD

**Issue by lucadello91** [spatie/laravel-enum#45]
Using HasEnums trait with HasTranslations trait on the same Model, cause collision error:

`Trait method setAttribute has not been applied, because there are collisions with other trait methods on Model`

How can I solve the problem in order to use both Traits in the Model?

**Comment by freekmurze** [comment]
I'm thinking this can't be solved right now, and we should take a look at this when we create a new major version of the package.

**Comment by Gummibeer** [comment]
You can use trait method aliasing and combine them in your own method. I think the `setAttribute()` method is the problem?
Both set methods in the traits are relatively simple.

@mstaack can possibly help you with a working example.
