### ISSUE TITLE
Plz update composer.json to version ^3.0

### ISSUE THREAD

**Issue by neatstudio** [spatie/laravel-enum#46]
Thanks , bcz i want to use xxx->label ，but 2.x has not this functional.
PLZ....

**Comment by Gummibeer** [comment]
Hey,

The Upgrade is already in progress #44 - but because v3 of the base package was a major release with breaking changes it's not a simple version bump.
But also v2 already offered labels and the possibility of a custom `toArray()` logic. They just had a different name in v2.
