### ISSUE TITLE
const MAP_VALUE working incorrect

### ISSUE THREAD

**Issue by pinkykitten** [spatie/laravel-enum#47]
My enum: 

```
<?php

namespace App\Enums;

use Spatie\Enum\Enum;

/**
 * @method static self WAITING_FOR_COMPANY_REPLY()
 * @method static self INVITE_INTERVIEW()
 * @method static self ACCEPT_INTERVIEW()
 * @method static self REJECT_INTERVIEW()
 * @method static self COMPANY_REJECT()
 */
class ApplyStatusEnum extends Enum
{
    const MAP_VALUE = [
        'WAITING_FOR_COMPANY_REPLY' => 1,
        'ACCEPT_INTERVIEW' => 2,
    ];
}

```

When I use `\App\Models\Apply::where('status', 1)->first()->status->getName()` it return `ACCEPT_INTERVIEW`.
It looks like *laravel-enum* use `index` 1 map to `ACCEPT_INTERVIEW` instance of use `value` 1 and map to `WAITING_FOR_COMPANY_REPLY`.

What did I do wrong?

**Comment by pinkykitten** [comment]
Sorry my mistake

**Comment by brendt** [comment]
Are you able to use v3 of the package? We're not going to actively support v2 anymore.

**Comment by Gummibeer** [comment]
Also for v2 it's not recommended to map only single values because of unexpected results.
Could you map all values and try again - if you can't upgrade to v3.

**Comment by pinkykitten** [comment]
Thank you for your reply!

Sorry, But where i can find v3 of this package? Current support is 1.6.0
![2020-09-03-162316_320x841_scrot](https://user-images.githubusercontent.com/7857371/92097717-9aa3e900-ee02-11ea-8227-ba157b809c43.png)
