### ISSUE TITLE
Failing tests because of stub whitespaces

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-enum#49]
Hey @Gummibeer I noticed some tests failing over here: https://github.com/spatie/laravel-enum/actions/runs/245897220

Any pointers on how I can fix them? I believe there's just some whitespacing missing in the stub files, but I wanted to check with you first. After those are fixed we'll be able to tag a release for L8

**Comment by Gummibeer** [comment]
Yeah, seems like the only "problem" is the empty line in the class body. 🤔
Could it be that your IDE "cleaned up" the snapshot file? 🧐🤔
Haven't checked history.

**Comment by brendt** [comment]
It was phpcs auto formatting them, I fixed it :)
