### ISSUE TITLE
Enum validation rule

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-enum#5]
Would it make sense to add one or more custom validation rules to validate request input?

**Comment by Gummibeer** [comment]
#13 isn't merged

**Comment by dennisoderwald** [comment]
@Gummibeer Is there a time estimate when the feature will be released?

**Comment by Gummibeer** [comment]
@dennisoderwald were you able to test it? `dev-ft-rules` as composer version should do the trick.
If you could give feedback it would be awesome. Otherwise I will wait for feedback by @brendt .
