### ISSUE TITLE
Nullable not working as expected

### ISSUE THREAD

**Issue by xewl** [spatie/laravel-enum#53]
The `nullable` cast gets validated as being an actual string value when using:

```php
protected $casts = [
   'status' => SomeStatusEnum::class.':nullable'
];
```

Exception: (`spatie\Enum` class) [expects a $value, "nullable" gets passed]
`There's no value "nullable" defined for enum SomeStatusEnum, consider adding it in the docblock definition.`

Removing the `:nullable` cast, also returns the exception that it's not passing (the expected number of) parameters
( see also spatie/enum#70 )

When I change it to eg. SomeStatusEnum::class.`:collection,nullable` the above occurs with constructor $value `"collection"`

**Comment by Gummibeer** [comment]
Does your `SomeStatusEnum` extend the laravel base enum or the enum class provided by `spatie/enum` package?

**Comment by xewl** [comment]
Oh. Good call... I might've overlooked that one when merging to the new version.
Indeed: `use Spatie\Enum\Enum;` (as that was the use-case of the previous version)

I don't see that change in the current readme eg either, so I probably didn't notice..
I'll retry my changes. [Might be good to put as a note somewhere? :) ]

**Comment by Gummibeer** [comment]
It's only for the cast support as this requires an interface and method. But I will add a long to the changelog if there's none.

**Comment by Gummibeer** [comment]
Have checked the changelog - there's this line:
> add Laravel focused base Enum class which implements Jsonable, Castable

**Comment by xewl** [comment]
@Gummibeer ^ having it in patch-1 for now. Will PR if that's what 
The readme does seem to have a notion of the class to use at `Usage › Model Attribute casting` too

Also looks like the address wasn't updated in this repository, yet :) (Kruikstraat 22 vs Samberstraat 69D)

**Comment by Gummibeer** [comment]
Thanks for your feedback, idea and also the work/fix you've done! 🎉🚀
Everything is merged now and should be clear enough now - as long as the user/dev reads the docs. 🙏
short list of commits:
* https://github.com/spatie/laravel-enum/commit/3ef37132ac79473e9f8877744717cccf2c0dc884
* https://github.com/spatie/laravel-enum/commit/7358b326f242e098a0b670e08c9c78166798e6c2
* https://github.com/spatie/enum/commit/7e2156adef41c7ae9fcd60ad4de26eeec45c9518
