### ISSUE TITLE
Get Label in Response

### ISSUE THREAD

**Issue by jatinthapar1910** [spatie/laravel-enum#59]
I am trying to achieve a functionality which allows to get label in response for the enum. 

Person.php
```
protected $casts = [
        'id' => 'integer',
        'first_name' => 'string',
        'last_name' => 'string',
        'email' => 'string',
        'type' => PersonEnum::class
    ];
```

PersonController.php
```
public function show(Request $request, $personId)
{
return Person::findOrFail($id);
}
```

PersonEnum.php
```
<?php

namespace App\Enums;

use Spatie\Enum\Laravel\Enum;

/**
 * @method static self Customer()
 * @method static self Supplier()
 */
final class PersonEnum extends Enum
{
    protected static function values(): array
    {
        return [
            'Customer' => 1,
            'Supplier' => 2
        ];
    }

    protected static function labels(): array
    {
        return [
            'Customer' => 'Customer',
            'Supplier' => 'Supplier',
        ];
    }
}

```

Expected JSON response
`"type": "Customer"` or `"type": "Supplier"`

Current Response: 
`"type": 1,`

**Comment by Gummibeer** [comment]
Hey,
I really really really don't recommend to use the model `toArray()`/`toJson()` functionality to return it as a response.
Instead I highly recommend [eloquent API resources](https://laravel.com/docs/8.x/eloquent-resources) which allow you to define more explicitly what you return and there you can use `$this->type->label` for example.
