### ISSUE TITLE
Collection validation

### ISSUE THREAD

**Issue by lucraraujo** [spatie/laravel-enum#61]
I have a list os value that I have encapsulated as enum. It's something like this:

```php
/**
 * @method static self VALUE1()
 * @method static self VALUE2()
 * @method static self VALUE3()
 */
final class FooEnum extends Enum
{}
```

And I can select one or more os theses values, I'm trying to validade if in the values I receive in the controller are valid.
The array I receive is something like this:
```php
$many_foo=[
    0 => 'VALUE1',
    1 => 'VALUE23'
];
```

And my validation is something like this:
```php
$request->validate([
   'many_foo' => ['required', new EnumRule(FooEnum::class)
]
```

**Comment by Gummibeer** [comment]
Hey,

you can use the asterisk to achieve this.

```php
$request->validate([
   'many_foo' => ['required', 'array'],
   'many_foo.*' => [new EnumRule(FooEnum::class)],
]);
```

**Comment by lucraraujo** [comment]
@Gummibeer Thanks man! It worked!
Sorry if a opened this issue on the wrong place, since my problem was a lack of knowledge on Laravel validation.
Thanks a lot!
