### ISSUE TITLE
Unexpected validation exception in Livewire

### ISSUE THREAD

**Issue by ju5t** [spatie/laravel-enum#63]
I'm trying to implement this package in a Livewire component. Some code to illustrate:

Our Enum:

```php
/**
 * @method static self BUSINESS()
 * @method static self HOUSEHOLD()
 */
final class CustomerType extends Enum
{
    protected static function values(): array
    {
        return [
            'BUSINESS' => 'business',
            'HOUSEHOLD' => 'household',
        ];
    }
}
```

Our Model:

```php
class Customer extends Model
{
...
    protected $casts = [
        'type' => CustomerType::class,
    ];
...
```

Our Livewire component:

```php
class CustomerEdit extends Component
{
...
    public $customer;

    protected function rules()
    {
        return [
            'customer.type' => 'enum:'.CustomerType::class,

...
```

I manipulate `customer.type` with a radio button. When I `@json` this on the rendered page, I get the `type` as a string. But as soon as I validate it, I get (thanks Ray!):

```
TypeError {#1745 ▼
  #message: "Only string and integer are allowed values for enum Domain\Customers\Enums\CustomerType."
  #code: 0
  #file: "my_app/vendor/spatie/enum/src/Enum.php"
  #line: 87
  trace: {▶}
}
```

This is coming from `passes(..)` in the `EnumRule`. It sets the value with:

```php
$this->asEnum($value);
```

But `$value` appears to be the `CustomerType` enum. It's not a string or integer. That's why it fails. I'm not sure why this happens. Should this be fixed in this package or are we doing something wrong?

**Comment by Gummibeer** [comment]
I think that's something special to livewire. So we have several ways.
* fix it in your own app
* transfer your fix in a livewire enum package
* come up with a solution in this package

The last one shouldn't conflict with a native Laravel app.

Potentially @brendt has an idea - I'm not using livewire until now.

Something I've seen in your validation rules: do you use the latest version? I don't think that it will fix your problem but a potential fix won't be pushed to an old version.

One idea to quickly fix it: add a `instanceof` check to the validation rule and return `true` if the value enum instance equals the wanted one.
This shouldn't conflict with native Laravel apps in any way.

**Comment by ju5t** [comment]
I spent quite some time on it this afternoon looking in what I now think was the wrong direction. You might be right that it is something special to Livewire. That apparently, didn't click earlier today :-(

I think it might have something to do with the hydration concept that is used there. I think that the property is casted there and passed along further to the validation as a casted property. I don't know if this is a bad thing or not. If it is, it needs to be changed in Livewire, if it is not, I think that warrants a change in this package.

> do you use the latest version?

Unfortunately not. As much as I like it that Spatie forces people to upgrade, it's not always doable in a larger application that uses several third party packages. We're still on PHP 7.4.

> One idea to quickly fix it: add a instanceof check to the validation rule and return true if the value enum instance equals the wanted one.

That's a good idea. I will use it as a workaround for now.

Let me know what you think about what I said above: if a change is needed in this package I'm more than happy to PR it.

**Comment by Gummibeer** [comment]
Hey,
The latest version is still for PHP 7.4
We haven't added PHP 8 only features. But have ideas to do - but not in nearest future.
Regarding the fix: I think that the package rule could get improved with the `instanceof` check.
So if you want to PR it - go for it! 🥳

**Comment by ju5t** [comment]
> The latest version is still for PHP 7.4

Something about assumptions.. I checked, we are using the latest version.

> So if you want to PR it - go for it! 🥳

Ok, will definitely do that soon!

**Comment by ju5t** [comment]
I will close this issue for now. Further discussion should probably take place in the PR.
