### ISSUE TITLE
Is is possible to use Enums on $attributes?

### ISSUE THREAD

**Issue by elfeffe** [spatie/laravel-enum#71]
I want to replace this code

```
protected $attributes = [
        'status' => self::STATUS_DRAFT,
    ];
```

But as far as I see, you can't.
```
protected $attributes = [
        'status' => StatusEnum::draft(),
    ];
```

That throws error

**Comment by Gummibeer** [comment]
Hey,
the error is right - as you can't assign object instances to default property values.
You could try something like:

```php
public function __construct($attributes)
{
    $this->attributes['status'] = StatusEnum::draft();

    parent::__construct($attributes);
}
```

The effect will be the same but you can use all values as you are inside a method.

**Comment by elfeffe** [comment]
I see, ok I will try that.
Thank you
