### ISSUE TITLE
getting error Laravel folder not found

### ISSUE THREAD

**Issue by creativitycomkw** [spatie/laravel-enum#76]
`use Spatie\Enum\Laravel\Enum;`

<img width="466" alt="Screen Shot 2021-06-07 at 4 22 55 PM" src="https://user-images.githubusercontent.com/66077942/121024139-9f8c3380-c7ac-11eb-918a-f756f3cfc7fc.png">

unable to use
`use Spatie\Enum\Laravel\Enum;`

**Comment by Gummibeer** [comment]
This looks like a corrupted autoloader. Have you tried to run `composer dump-autoload`? And if that doesn't help delete `vendor` directory and `composer.lock` and run `conposer update`.

**Comment by creativitycomkw** [comment]
i tried almost everything but still same error

<img width="1202" alt="Screen Shot 2021-06-08 at 9 20 16 AM" src="https://user-images.githubusercontent.com/66077942/121133256-cc872780-c83a-11eb-92a2-c53c2ac19973.png">
