### ISSUE TITLE
Unable to groupBy a Collection Using an Enum as a Criteria when Casting

### ISSUE THREAD

**Issue by viniciushss-interstar** [spatie/laravel-enum#78]
Hi there,

Sorry if I'm doing something wrong but there's a problem when using an enum as model attribute and the attribute is used in the method `groupBy` of a Eloquent Collection. Example:

The model:
```php
use Illuminate\Database\Eloquent\Model;

class TestModel extends Model
{
    protected $casts = [
        'status' => StatusEnum::class,
    ];
}
```

The problem with [groupBy](https://laravel.com/docs/8.x/collections#method-groupby):
```php
$testModels = TestModel::all;

$testModels->groupBy('status');
```

The return is:

> TypeError
> `array_key_exists()`: Argument #1 ($key) must be a valid array offset type in `vendor/laravel/framework/src/Illuminate/Collections/Collection.php:445`

If I remove the cast from the model, it works fine, using the value as array key. Any suggestions?

Thanks!

**Comment by Gummibeer** [comment]
The fastest way would be to use the closure option for `groupBy()` and return the string value yourself.
I'm pretty sure/optimistic that things like this will get better with PHP8.1 native enums and the things we can do with them then.

```php
$testModels->groupBy(fn(TestModel $m): string => $m->status->value));
```

**Comment by viniciushss-interstar** [comment]
Thank you, that worked nicely.
