### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-enum#8]
Implement all the linked CI tools:
* [x] TravisCI https://travis-ci.org/spatie/laravel-enum
* [x] StyleCI
* [x] ScrutinizerCI https://scrutinizer-ci.com/g/spatie/laravel-enum/
* [x] CoverallsIO https://coveralls.io/github/spatie/laravel-enum

**Comment by Gummibeer** [comment]
@freekmurze could you enable the missing StyleCI?

**Comment by freekmurze** [comment]
Done
