### ISSUE TITLE
Custom validation message for EnumValue

### ISSUE THREAD

**Issue by alexandruu** [spatie/laravel-enum#88]
Hy,

I have a Form Request with a custom validation rule:

`$rules = [
            'input.value' => ['required', new EnumValue(ValueEnum::class, false)],
];`

Validation works fine but the message received is ambiguous:

> The value you have entered is invalid.

Is there a way to change this message to include at least the attribute in it?

**Comment by Gummibeer** [comment]
The `EnumRule` defines a fully customizable validation message.
https://github.com/spatie/laravel-enum/blob/c383b730a9f6d9dcc621fc87f9ec586ab791167a/src/Rules/EnumRule.php#L52-L59

But your code example seems like you are using an old outdated version.

**Comment by alexandruu** [comment]
Thank you!
