### ISSUE TITLE
v1 => v2 and v2 => v3 upgrade guides

### ISSUE THREAD

**Issue by tmas** [spatie/laravel-enum#95]
I'm attempting to upgrade a project from version 1.6.1 of this package to the latest version, but I can't find a list of breaking changes or any recommendations to work around them.

A full upgrade guide would be awesome, but even just some basic info (e.g. for any model that uses the `HasEnum` attribute, we recommend doing X) would be very helpful.

Thanks!

**Comment by Gummibeer** [comment]
Have you checked the [Changelog](https://github.com/spatie/laravel-enum/blob/main/CHANGELOG.md)?
